"""add_crs_pattern_to_sessions

Revision ID: 9671358ce69b
Revises: cf5bc0b34108
Create Date: 2026-01-24 15:46:50.348074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9671358ce69b'
down_revision: Union[str, Sequence[str], None] = 'cf5bc0b34108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('crs_pattern', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'crs_pattern')
    # ### end Alembic commands ###
