"""add_crs_audit_log

Revision ID: c961cde4f0b0
Revises: 54819465f436
Create Date: 2026-01-08 19:47:39.383446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c961cde4f0b0'
down_revision: Union[str, Sequence[str], None] = '54819465f436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crs_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crs_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('old_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['crs_id'], ['crs_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crs_audit_logs_crs_id'), 'crs_audit_logs', ['crs_id'], unique=False)
    op.create_index(op.f('ix_crs_audit_logs_id'), 'crs_audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crs_audit_logs_id'), table_name='crs_audit_logs')
    op.drop_index(op.f('ix_crs_audit_logs_crs_id'), table_name='crs_audit_logs')
    op.drop_table('crs_audit_logs')
    # ### end Alembic commands ###
