"""Add google login fields

Revision ID: da39b33a35ad
Revises: ae068e1e14c7
Create Date: 2026-02-01 10:58:32.615406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da39b33a35ad'
down_revision: Union[str, Sequence[str], None] = 'ae068e1e14c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_id')
    op.create_index(op.f('idx_session_project_status'), 'sessions', ['project_id', 'status'], unique=False)
    op.create_index(op.f('idx_project_team_status'), 'projects', ['team_id', 'status'], unique=False)
    op.create_index(op.f('idx_project_team_created'), 'projects', ['team_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.create_index(op.f('idx_crs_project_status'), 'crs_documents', ['project_id', 'status'], unique=False)
    op.alter_column('crs_documents', 'edit_version',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.create_table('invitations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invited_by_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'accepted', 'expired', 'canceled'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('invitations_ibfk_2')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('invitations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitations_team_id'), 'invitations', ['team_id'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    # ### end Alembic commands ###
